common:
  x_start: 0
  x_end: 20
  t_start: 0
  t_end: 1
  J: 64
  dx: 0.3125
  timesteps: 500
  dt: 0.002
  N_samples: 2000
  periodic: true
  prediction_samples: 200
  lasso_drift_lambda: 0.2
  sindy_drift_lambda: 0.3
  lasso_diffusion_lambda: 0.1
  sindy_diffusion_lambda: 0.1
kdv:
  initial_condition: sin(x)
  correct:
    drift:
      epsilon: 0
      uu_x_coeff: -1
      u_xxx_coeff: -1
    diffusion:
      sigma: 1
  discovered:
    drift:
      u2_coeff: 0.056186
      u2_coeff_variance: 0.00168398
      u3_coeff: 0.132927
      u3_coeff_variance: 0.00389237
      uu_x_coeff: -0.863004
      uu_x_coeff_variance: 0.00079239
      epsilon: 0.098651
      epsilon_variance: 4.052e-05
      u_xxx_coeff: -1.001541
      u_xxx_coeff_variance: 8.55e-06
      u_coeff: 0.044457
      u_coeff_variance: 0.00059362
    diffusion:
      sigma_squared: 0.985641
      sigma_squared_variance: 1.234e-05
      u_coeff: -0.049481
      u_coeff_variance: 8.912e-05
      u2_coeff: -0.038467
      u2_coeff_variance: 0.00032261
      u3_coeff: 0.189536
      u3_coeff_variance: 0.00060326
      epsilon: -0.026348
      epsilon_variance: 6.13e-06
      uu_x_coeff: -0.17537
      uu_x_coeff_variance: 0.00073096
heat:
  initial_condition: sin(x)
  correct:
    drift:
      epsilon: 1
    diffusion:
      sigma: 1
  discovered:
    drift:
      u_coeff: -0.091959
      u_coeff_variance: 0.0039281
      u2_coeff: 0.111173
      u2_coeff_variance: 0.01239364
      u3_coeff: 0.065169
      u3_coeff_variance: 0.00694806
      epsilon: 0.996246
      epsilon_variance: 0.00033519
    diffusion:
      sigma_squared: 0.968982
      sigma_squared_variance: 2.46e-06
      u2_coeff: -0.018357
      u2_coeff_variance: 5.603e-05
allen_cahn:
  initial_condition: sin(x)
  correct:
    drift:
      epsilon: 1
      u_coeff: 1
      u3_coeff: -1
    diffusion:
      sigma: 1
  discovered:
    drift:
      sigma_squared: -0.020932
      sigma_squared_variance: 0.0003527
      u_coeff: 1.016239
      u_coeff_variance: 0.0045439
      u2_coeff: 0.32696
      u2_coeff_variance: 0.03952026
      u3_coeff: -0.980924
      u3_coeff_variance: 0.01249101
      uu_x_coeff: 0.256926
      uu_x_coeff_variance: 0.03736228
      epsilon: 0.984659
      epsilon_variance: 0.0002796
    diffusion:
      sigma_squared: 0.969832
      sigma_squared_variance: 1.4e-06
      uu_x_coeff: 0.011694
      uu_x_coeff_variance: 0.00012799
nagumo:
  initial_condition: cos(x)
  correct:
    drift:
      epsilon: 1
      alpha: -0.5
      u_coeff: 0.5
      u2_coeff: 0.5
      u3_coeff: -1
    diffusion:
      sigma: 1
  discovered:
    drift:
      sigma_squared: -0.018067
      sigma_squared_variance: 0.00095978
      u_coeff: 0.49319
      u_coeff_variance: 0.00425711
      u2_coeff: 0.631217
      u2_coeff_variance: 0.04258118
      u3_coeff: -1.022627
      u3_coeff_variance: 0.02968556
      epsilon: 0.976794
      epsilon_variance: 0.00060083
    diffusion:
      sigma_squared: 0.967996
      sigma_squared_variance: 3.85e-06
