common:
  x_start: 0
  x_end: 20
  t_start: 0
  t_end: 1
  J: 64
  dx: 0.3125
  timesteps: 500
  dt: 0.002
  N_samples: 2000
  periodic: true
  prediction_samples: 200
  lasso_drift_lambda: 0.2
  sindy_drift_lambda: 0.3
  lasso_diffusion_lambda: 0.1
  sindy_diffusion_lambda: 0.1
kdv:
  initial_condition: sin(x)
  correct:
    drift:
      epsilon: 0
      uu_x_coeff: -1
      u_xxx_coeff: -1
    diffusion:
      sigma: 1
  discovered:
    drift:
      u2_coeff: 0.056186
      u2_coeff_variance: 0.00237471
      u3_coeff: 0.132927
      u3_coeff_variance: 0.00321256
      uu_x_coeff: -0.863004
      uu_x_coeff_variance: 0.00173155
      epsilon: 0.098651
      epsilon_variance: 4.052e-05
      u_xxx_coeff: -1.001541
      u_xxx_coeff_variance: 1.381e-05
      u_coeff: 0.044457
      u_coeff_variance: 0.00059362
    diffusion:
      sigma_squared: 0.985641
      sigma_squared_variance: 1.231e-05
      u_coeff: -0.049481
      u_coeff_variance: 9.576e-05
      u2_coeff: -0.038467
      u2_coeff_variance: 0.00034193
      u3_coeff: 0.189536
      u3_coeff_variance: 0.00062251
      epsilon: -0.026348
      epsilon_variance: 6.07e-06
      uu_x_coeff: -0.17537
      uu_x_coeff_variance: 0.00035075
heat:
  initial_condition: sin(x)
  correct:
    drift:
      epsilon: 1
    diffusion:
      sigma: 1
  discovered:
    drift:
      u_coeff: -0.091959
      u_coeff_variance: 0.00419415
      u2_coeff: 0.111173
      u2_coeff_variance: 0.01670689
      u3_coeff: 0.065169
      u3_coeff_variance: 0.0142465
      epsilon: 0.996246
      epsilon_variance: 0.00043885
      uu_x_coeff: -0.174817
      uu_x_coeff_variance: 0.00944474
    diffusion:
      sigma_squared: 0.968982
      sigma_squared_variance: 2.61e-06
      u2_coeff: -0.018357
      u2_coeff_variance: 5.603e-05
      u3_coeff: 0.010876
      u3_coeff_variance: 4.883e-05
allen_cahn:
  initial_condition: sin(x)
  correct:
    drift:
      epsilon: 1
      u_coeff: 1
      u3_coeff: -1
    diffusion:
      sigma: 1
  discovered:
    drift:
      sigma_squared: -0.020932
      sigma_squared_variance: 0.00035793
      u_coeff: 1.016239
      u_coeff_variance: 0.00475012
      u2_coeff: 0.32696
      u2_coeff_variance: 0.0407521
      u3_coeff: -0.980924
      u3_coeff_variance: 0.0139908
      uu_x_coeff: 0.256926
      uu_x_coeff_variance: 0.06062217
      epsilon: 0.984659
      epsilon_variance: 0.0002996
    diffusion:
      sigma_squared: 0.969832
      sigma_squared_variance: 1.67e-06
      uu_x_coeff: 0.011694
      uu_x_coeff_variance: 0.00024928
nagumo:
  initial_condition: cos(x)
  correct:
    drift:
      epsilon: 1
      alpha: -0.5
      u_coeff: 0.5
      u2_coeff: 0.5
      u3_coeff: -1
    diffusion:
      sigma: 1
  discovered:
    drift:
      sigma_squared: -0.018067
      sigma_squared_variance: 0.00099551
      u_coeff: 0.49319
      u_coeff_variance: 0.00435475
      u2_coeff: 0.631217
      u2_coeff_variance: 0.05071608
      u3_coeff: -1.022627
      u3_coeff_variance: 0.03527165
      epsilon: 0.976794
      epsilon_variance: 0.00070447
    diffusion:
      sigma_squared: 0.967996
      sigma_squared_variance: 4.0e-06
      u2_coeff: 0.017815
      u2_coeff_variance: 0.00020563
      uu_x_coeff: 0.012897
      uu_x_coeff_variance: 0.00027506
