common:
  x_start: 0
  x_end: 20
  t_start: 0
  t_end: 1
  J: 64
  dx: 0.3125
  timesteps: 500
  dt: 0.002
  N_samples: 2000
  periodic: true
  prediction_samples: 200
  lasso_drift_lambda: 0.2
  sindy_drift_lambda: 0.3
  lasso_diffusion_lambda: 0.1
  sindy_diffusion_lambda: 0.1
kdv:
  initial_condition: sin(x)
  correct:
    epsilon: 0
    sigma: 1
    uu_x_coeff: -1
    u_xxx_coeff: -1
  discovered:
    u_coeff: -0.079095
    u_coeff_variance: 0.00026857
    u2_coeff: -0.062538
    u2_coeff_variance: 0.00189952
    u3_coeff: 0.340024
    u3_coeff_variance: 0.00233767
    sigma_squared: 1.00369
    sigma_squared_variance: 2.051e-05
    epsilon: -0.04133
    epsilon_variance: 2.979e-05
    uu_x_coeff: 0.056854
    uu_x_coeff_variance: 0.00269769
    u_xxx_coeff: -0.032517
    u_xxx_coeff_variance: 2.85e-05
heat:
  initial_condition: sin(x)
  correct:
    epsilon: 1
    sigma: 1
  discovered:
    epsilon: 0.987903
    epsilon_variance: 0.00064315
    sigma_squared: 0.968097
    sigma_squared_variance: 4.07e-06
    u_coeff: -0.141364
    u_coeff_variance: 0.020531
    u3_coeff: 0.042532
    u3_coeff_variance: 0.0013689
    u2_coeff: -0.012682
    u2_coeff_variance: 0.00053975
    uu_x_coeff: -0.106556
    uu_x_coeff_variance: 0.05510237
    u_xxx_coeff: 0.034234
    u_xxx_coeff_variance: 0.00053546
allen_cahn:
  initial_condition: sin(x)
  correct:
    epsilon: 1
    sigma: 1
    u_coeff: 1
    u3_coeff: -1
  discovered:
    epsilon: 0.920259
    epsilon_variance: 0.00390938
    u_coeff: 0.01387
    u_coeff_variance: 9.868e-05
    u3_coeff: -0.023984
    u3_coeff_variance: 0.00425512
    sigma: null
    sigma_variance: null
    sigma_squared: 0.969662
    sigma_squared_variance: 3.31e-06
    u2_coeff: -0.013276
    u2_coeff_variance: 0.00092597
    uu_x_coeff: -0.010715
    uu_x_coeff_variance: 0.00069697
nagumo:
  initial_condition: cos(x)
  correct:
    epsilon: 1
    sigma: 1
    alpha: -0.5
    u_coeff: 0.5
    u2_coeff: 0.5
    u3_coeff: -1
  discovered:
    epsilon: 0.963642
    epsilon_variance: 0.00088354
    u_coeff: -0.011003
    u_coeff_variance: 0.00014444
    u2_coeff: 0.741659
    u2_coeff_variance: 0.27725588
    u3_coeff: 0.037622
    u3_coeff_variance: 0.0053417
    sigma: null
    sigma_variance: null
    sigma_squared: 0.966714
    sigma_squared_variance: 6.32e-06
    uu_x_coeff: 0.017884
    uu_x_coeff_variance: 0.00060031
    u_xxx_coeff: 0.030412
    u_xxx_coeff_variance: 0.00038085
